# Configuration optimized for indoor lighting conditions
reference:
  size: 10
  min_area: 1000
  max_area: 100000
  edge_detection:
    low_threshold: 40 # Lower threshold for indoor lighting
    high_threshold: 120
  contour_approximation:
    epsilon_factor: 0.02

detection:
  confidence_threshold: 0.65 # More lenient detection
  edge_detection:
    low_threshold: 40
    high_threshold: 120
  min_object_size: 20
  max_objects: 50

measurement:
  min_object_size: 1
  max_object_size: 100
  precision: 2

visualization:
  colors:
    reference: [0, 255, 0]
    object: [0, 0, 255]
    text: [255, 255, 255]
  text:
    font_scale: 0.8
    thickness: 2
