# Configuration for 15x15cm reference card (larger objects)
reference:
  size: 15 # Reference card size in cm
  min_area: 2000 # Larger area for bigger card
  max_area: 150000
  edge_detection:
    low_threshold: 60
    high_threshold: 180
  contour_approximation:
    epsilon_factor: 0.025

detection:
  confidence_threshold: 0.75
  edge_detection:
    low_threshold: 60
    high_threshold: 180
  min_object_size: 30
  max_objects: 50

measurement:
  min_object_size: 2
  max_object_size: 200
  precision: 1

visualization:
  colors:
    reference: [0, 255, 0]
    object: [0, 0, 255]
    text: [255, 255, 255]
  text:
    font_scale: 1.0
    thickness: 2
